<a href="https://colab.research.google.com/github/MdBilal420/DL-tensors/blob/main/tensors_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
tensor_zero_d = tf.constant(5)
print(tensor_zero_d)

tf.Tensor(5, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2,0,-4])

In [ ]:
print(tensor_one_d)

tf.Tensor([ 2  0 -4], shape=(3,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
    [2,3,5],
    [-3,5,7],
    [1,5,9]
])
print(tensor_two_d)

tf.Tensor(
[[ 2  3  5]
 [-3  5  7]
 [ 1  5  9]], shape=(3, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
        [[ 2,  3,  5],
         [-3,  5,  7]],

        [[ 1,  -3,  6],
         [-4,  8,  -7]],

])
print(tensor_three_d)


tf.Tensor(
[[[ 2  3  5]
  [-3  5  7]]

 [[ 1 -3  6]
  [-4  8 -7]]], shape=(2, 2, 3), dtype=int32)


In [ ]:
tensor_four_d = tf.constant([
    [[[ 2,  3,  5],
      [-3,  5,  7]],

      [[ 1,  -3,  6],
      [-4,  8,  -7]],],

    [[[ -2,  -3,  -5],
      [3,  -5,  -7]],

      [[ -1,  3,  -6],
      [4,  -8,  7]],],

    [[[ -2,  -3,  -5],
      [3,  -5,  -7]],

      [[ 11,  -33,  46],
      [-42,  38,  -37]],]
])
print(tensor_four_d)


tf.Tensor(
[[[[  2   3   5]
   [ -3   5   7]]

  [[  1  -3   6]
   [ -4   8  -7]]]


 [[[ -2  -3  -5]
   [  3  -5  -7]]

  [[ -1   3  -6]
   [  4  -8   7]]]


 [[[ -2  -3  -5]
   [  3  -5  -7]]

  [[ 11 -33  46]
   [-42  38 -37]]]], shape=(3, 2, 2, 3), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2.3,0,-4.0])
casted_tensor_one_d = tf.cast(tensor_one_d,dtype=tf.bool)
print(tensor_one_d)
print(casted_tensor_one_d)


tf.Tensor([ 2.3  0.  -4. ], shape=(3,), dtype=float32)
tf.Tensor([ True False  True], shape=(3,), dtype=bool)
